# =============================================================================
# CONFIGURACIÓN LANDO - ECOSISTEMA JARABA SAAS
# =============================================================================
# COMANDOS:
#   lando start    - Iniciar entorno
#   lando drush    - Ejecutar Drush
#   lando composer - Ejecutar Composer
#
# URL: https://jaraba-saas.lndo.site
# =============================================================================

name: jaraba-saas
recipe: drupal11

config:
  webroot: web
  php: "8.4"
  via: apache
  config:
    php: php.ini

# Variables de entorno para el appserver
env_file:
  - .env

# =============================================================================
# SERVICIOS
# =============================================================================

services:
  # ─────────────────────────────────────────────────────
  # APPSERVER - Override para variables de entorno Redis
  # ─────────────────────────────────────────────────────
  appserver:
    overrides:
      environment:
        LANDO: 'ON'
        REDIS_HOST: redis
        REDIS_PORT: '6379'
        QDRANT_HOST: qdrant
        QDRANT_PORT: '6333'
        QDRANT_DEV_API_KEY: ${QDRANT_DEV_API_KEY:-jaraba-dev-qdrant-key-2026}

  database:
    type: mariadb:10.11
    # LOW-12: Using 3306 (standard) instead of 3310 to match tooling defaults.
    portforward: 3306
    creds:
      user: drupal
      password: drupal
      database: drupal_jaraba

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

  # ─────────────────────────────────────────────────────
  # REDIS - Cache Backend para Drupal
  # ─────────────────────────────────────────────────────
  # Mejora rendimiento y reduce costes de IA (cache de respuestas)
  # CLI: lando redis-cli
  # ─────────────────────────────────────────────────────
  redis:
    type: redis:7
    portforward: 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ─────────────────────────────────────────────────────
  # QDRANT - Base de Datos Vectorial para RAG (KB AI-Nativa)
  # ─────────────────────────────────────────────────────
  # URLs de acceso:
  #   - Desde Drupal (interno): http://qdrant:6333
  #   - Desde navegador (externo): http://qdrant.jaraba-saas.lndo.site:6333
  #   - Dashboard UI: http://qdrant.jaraba-saas.lndo.site:6333/dashboard
  # Documentación: docs/tecnicos/20260110i-Anexo_A_Knowledge_Base_AI_Nativa_claude.md
  # ─────────────────────────────────────────────────────
  qdrant:
    type: compose
    services:
      image: qdrant/qdrant:latest
      command: "./qdrant"
      ports:
        - "6333:6333"
        - "6334:6334"
      environment:
        QDRANT__SERVICE__GRPC_PORT: "6334"
        QDRANT__SERVICE__API_KEY: ${QDRANT_DEV_API_KEY:-jaraba-dev-qdrant-key-2026}
      # Healthcheck añadido tras Game Day #1 (2026-01-11)
      healthcheck:
        test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s

  # ─────────────────────────────────────────────────────
  # TIKA - Procesamiento de Documentos para RAG
  # ─────────────────────────────────────────────────────
  # Extrae texto de PDF, Word, etc. para indexación en Qdrant
  # Endpoint: http://tika:9998
  # ─────────────────────────────────────────────────────
  tika:
    type: compose
    services:
      image: apache/tika
      command: /bin/sh -c 'exec java -jar /tika-server-standard-*.jar -h 0.0.0.0'
      ports:
        - '9998:9998'

  # ─────────────────────────────────────────────────────
  # MAILHOG - Testing de Email
  # ─────────────────────────────────────────────────────
  # UI: http://mail.jaraba-saas.lndo.site
  # SMTP: mailhog:1025
  # ─────────────────────────────────────────────────────
  mailhog:
    type: mailhog
    portforward: 8025
    hogfrom:
      - appserver

  # ─────────────────────────────────────────────────────
  # PROMETHEUS & GRAFANA - DESACTIVADOS TEMPORALMENTE
  # ─────────────────────────────────────────────────────
  # Causa inestabilidad con Lando en Docker Desktop 4.55.0
  # El Dashboard de Salud de Drupal (/admin/health) cubre
  # las necesidades de monitoreo.
  # 
  # Para usar Grafana/Prometheus, ejecutar directamente:
  #   docker run -d -p 3000:3000 grafana/grafana
  #   docker run -d -p 9090:9090 prom/prometheus
  # ─────────────────────────────────────────────────────

# =============================================================================
# PROXY
# =============================================================================
# Dominios disponibles:
#   - jaraba-saas.lndo.site (plataforma principal)
#   - *.jaraba-saas.lndo.site (subdominios de tenants)
# =============================================================================

proxy:
  appserver:
    - jaraba-saas.lndo.site
    # Subdominios de Tenants
    - aceitesdelsur.jaraba-saas.lndo.site
    # Marca Personal Pepe Jaraba (dev proxy)
    - pepejaraba.jaraba-saas.lndo.site
    # Institucional B2B Jaraba Impact (dev proxy)
    - jarabaimpact.jaraba-saas.lndo.site
    # Corporativo Legal PED S.L. (dev proxy)
    - plataformadeecosistemas.jaraba-saas.lndo.site
  phpmyadmin:
    - phpmyadmin.jaraba-saas.lndo.site
  qdrant:
    - qdrant.jaraba-saas.lndo.site:6333
  mailhog:
    - mail.jaraba-saas.lndo.site

# =============================================================================
# TOOLING
# =============================================================================

tooling:
  php:
    service: appserver
  composer:
    service: appserver
  drush:
    service: appserver
  
  # Redis CLI
  redis-cli:
    service: redis
    description: Ejecutar comandos Redis
    cmd: redis-cli

  # Redis Status
  redis-status:
    service: appserver
    description: Verificar estado de Redis
    cmd: |
      echo "=== Redis Connection Test ==="
      php -r "
        \$redis = new Redis();
        \$redis->connect('redis', 6379);
        echo 'PING: ' . \$redis->ping() . PHP_EOL;
        echo 'Memory Used: ' . \$redis->info('memory')['used_memory_human'] . PHP_EOL;
        echo 'Keys: ' . \$redis->dbSize() . PHP_EOL;
      "

  # Qdrant Status
  qdrant-status:
    service: appserver
    description: Ver colecciones de Qdrant
    cmd: curl -s -H "Api-Key:${QDRANT_DEV_API_KEY:-jaraba-dev-qdrant-key-2026}" http://qdrant:6333/collections | jq

  # Qdrant Health
  qdrant-health:
    service: appserver
    description: Health check de Qdrant
    cmd: curl -s -H "Api-Key:${QDRANT_DEV_API_KEY:-jaraba-dev-qdrant-key-2026}" http://qdrant:6333/healthz

  # Tika Test
  tika-test:
    service: appserver
    description: Verificar Apache Tika
    cmd: |
      echo "Testing Tika connection..."
      curl -s http://tika:9998/tika | head -20

  # AI Stack Health Check
  ai-health:
    service: appserver
    description: Verificar todo el stack de IA
    cmd: |
      echo "═══════════════════════════════════════"
      echo "       AI STACK HEALTH CHECK"
      echo "═══════════════════════════════════════"
      echo ""
      echo "1. Redis..."
      php -r "\$r = new Redis(); \$r->connect('redis', 6379); echo \$r->ping() . PHP_EOL;" 2>/dev/null || echo "FAILED"
      echo ""
      echo "2. Qdrant..."
      curl -s -H "Api-Key:${QDRANT_DEV_API_KEY:-jaraba-dev-qdrant-key-2026}" http://qdrant:6333/healthz && echo " OK" || echo " FAILED"
      echo ""
      echo "3. Tika..."
      curl -s -o /dev/null -w "%{http_code}" http://tika:9998/tika && echo " OK" || echo " FAILED"
      echo ""
      echo "═══════════════════════════════════════"

  # Instalar Drupal
  install-drupal:
    service: appserver
    description: Instalar Drupal desde cero
    cmd: |
      drush site:install standard \
        --db-url=mysql://drupal:drupal@database:3306/drupal_jaraba \
        --site-name="Ecosistema Jaraba" \
        --account-name=admin \
        --account-pass=admin \
        --yes

  # Habilitar módulo core
  enable-core:
    service: appserver
    description: Habilitar ecosistema_jaraba_core
    cmd: drush en ecosistema_jaraba_core -y && drush cr

  # Exportar configuración
  export-config:
    service: appserver
    cmd: drush cex -y

  # Importar configuración
  import-config:
    service: appserver
    cmd: drush cim -y

  # Cache Clear rápido
  cr:
    service: appserver
    description: Limpiar cache Drupal
    cmd: drush cr

  # ─────────────────────────────────────────────────────
  # SELF-HEALING - Comandos de auto-recuperación
  # Basado en Game Day #1 (2026-01-11)
  # ─────────────────────────────────────────────────────
  
  self-heal:
    service: appserver
    description: Ejecutar todos los checks de self-healing
    cmd: /app/scripts/self-healing/run-all.sh

  self-heal-db:
    service: appserver
    description: Check y recovery de base de datos
    cmd: /app/scripts/self-healing/db-health.sh

  self-heal-qdrant:
    service: appserver
    description: Check y recovery de Qdrant
    cmd: /app/scripts/self-healing/qdrant-health.sh

  self-heal-cache:
    service: appserver
    description: Check y recovery de cache
    cmd: /app/scripts/self-healing/cache-recovery.sh

