# =============================================================================
# CONFIGURACIÓN LANDO - ECOSISTEMA JARABA SAAS
# =============================================================================
# COMANDOS:
#   lando start    - Iniciar entorno
#   lando drush    - Ejecutar Drush
#   lando composer - Ejecutar Composer
#
# URL: https://jaraba-saas.lndo.site
# =============================================================================

name: jaraba-saas
recipe: drupal11

config:
  webroot: web
  php: "8.4"
  via: apache
  config:
    php: php.ini

# =============================================================================
# SERVICIOS
# =============================================================================

services:
  database:
    type: mariadb:10.11
    portforward: 3310
    creds:
      user: drupal
      password: drupal
      database: drupal_jaraba

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

  # ─────────────────────────────────────────────────────
  # QDRANT - Base de Datos Vectorial para RAG (KB AI-Nativa)
  # ─────────────────────────────────────────────────────
  # URLs de acceso:
  #   - Desde Drupal (interno): http://qdrant:6333
  #   - Desde navegador (externo): http://qdrant.jaraba-saas.lndo.site:6333
  #   - Dashboard UI: http://qdrant.jaraba-saas.lndo.site:6333/dashboard
  # Documentación: docs/tecnicos/20260110i-Anexo_A_Knowledge_Base_AI_Nativa_claude.md
  # ─────────────────────────────────────────────────────
  qdrant:
    type: compose
    services:
      image: qdrant/qdrant:latest
      command: "./qdrant"
      ports:
        - "6333:6333"
        - "6334:6334"
      environment:
        QDRANT__SERVICE__GRPC_PORT: "6334"
      # Healthcheck añadido tras Game Day #1 (2026-01-11)
      healthcheck:
        test: ["CMD", "wget", "-q", "--spider", "http://localhost:6333/"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 10s

  # ─────────────────────────────────────────────────────
  # PROMETHEUS - Recolección de Métricas
  # ─────────────────────────────────────────────────────
  # URL: http://prometheus.jaraba-saas.lndo.site:9090
  # ─────────────────────────────────────────────────────
  prometheus:
    type: compose
    services:
      image: prom/prometheus:latest
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.enable-lifecycle'
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus:/etc/prometheus

  # ─────────────────────────────────────────────────────
  # GRAFANA - Dashboard de Observabilidad
  # ─────────────────────────────────────────────────────
  # URL: http://grafana.jaraba-saas.lndo.site:3000
  # Credenciales: admin / jaraba123
  # ─────────────────────────────────────────────────────
  grafana:
    type: compose
    services:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: jaraba123
        GF_USERS_ALLOW_SIGN_UP: "false"
      volumes:
        - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
        - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

# =============================================================================
# PROXY
# =============================================================================
# Dominios disponibles:
#   - jaraba-saas.lndo.site (plataforma principal)
#   - *.jaraba-saas.lndo.site (subdominios de tenants)
# =============================================================================

proxy:
  appserver:
    - jaraba-saas.lndo.site
    # Subdominios de Tenants
    - aceitesdelsur.jaraba-saas.lndo.site
    # Añadir más subdominios según se creen tenants
  phpmyadmin:
    - phpmyadmin.jaraba-saas.lndo.site
  qdrant:
    - qdrant.jaraba-saas.lndo.site:6333
  # Observability Stack
  grafana:
    - grafana.jaraba-saas.lndo.site:3000
  prometheus:
    - prometheus.jaraba-saas.lndo.site:9090

# =============================================================================
# TOOLING
# =============================================================================

tooling:
  php:
    service: appserver
  composer:
    service: appserver
  drush:
    service: appserver

  # Instalar Drupal
  install-drupal:
    service: appserver
    description: Instalar Drupal desde cero
    cmd: |
      drush site:install standard \
        --db-url=mysql://drupal:drupal@database:3306/drupal_jaraba \
        --site-name="Ecosistema Jaraba" \
        --account-name=admin \
        --account-pass=admin \
        --yes

  # Habilitar módulo core
  enable-core:
    service: appserver
    description: Habilitar ecosistema_jaraba_core
    cmd: drush en ecosistema_jaraba_core -y && drush cr

  # Exportar configuración
  export-config:
    service: appserver
    cmd: drush cex -y

  # Importar configuración
  import-config:
    service: appserver
    cmd: drush cim -y

  # ─────────────────────────────────────────────────────
  # SELF-HEALING - Comandos de auto-recuperación
  # Basado en Game Day #1 (2026-01-11)
  # ─────────────────────────────────────────────────────
  
  self-heal:
    service: appserver
    description: Ejecutar todos los checks de self-healing
    cmd: /app/scripts/self-healing/run-all.sh

  self-heal-db:
    service: appserver
    description: Check y recovery de base de datos
    cmd: /app/scripts/self-healing/db-health.sh

  self-heal-qdrant:
    service: appserver
    description: Check y recovery de Qdrant
    cmd: /app/scripts/self-healing/qdrant-health.sh

  self-heal-cache:
    service: appserver
    description: Check y recovery de cache
    cmd: /app/scripts/self-healing/cache-recovery.sh
