<?php

declare(strict_types=1);

namespace Drupal\jaraba_ai_agents\Entity;

use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Defines the Aggregated Insight entity.
 *
 * Stores cross-tenant anonymized insights generated by FederatedInsightService.
 * k-anonymity enforced: minimum 5 tenants must contribute to an insight.
 * No raw tenant data is stored — only aggregated statistics.
 *
 * @ContentEntityType(
 *   id = "aggregated_insight",
 *   label = @Translation("Aggregated Insight"),
 *   label_collection = @Translation("Aggregated Insights"),
 *   label_singular = @Translation("aggregated insight"),
 *   label_plural = @Translation("aggregated insights"),
 *   handlers = {
 *     "view_builder" = "Drupal\Core\Entity\EntityViewBuilder",
 *     "list_builder" = "Drupal\Core\Entity\EntityListBuilder",
 *     "views_data" = "Drupal\views\EntityViewsData",
 *     "route_provider" = {
 *       "html" = "Drupal\Core\Entity\Routing\AdminHtmlRouteProvider",
 *     },
 *   },
 *   base_table = "aggregated_insight",
 *   admin_permission = "administer ai agents",
 *   entity_keys = {
 *     "id" = "id",
 *     "uuid" = "uuid",
 *   },
 *   links = {
 *     "collection" = "/admin/content/ai/federated-insights",
 *     "canonical" = "/admin/content/ai/federated-insights/{aggregated_insight}",
 *   },
 * )
 */
class AggregatedInsight extends ContentEntityBase implements ContentEntityInterface {

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type): array {
    $fields = parent::baseFieldDefinitions($entity_type);

    $fields['insight_type'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Insight Type'))
      ->setDescription(t('Category of the aggregated insight.'))
      ->setRequired(TRUE)
      ->setSetting('allowed_values', [
        'industry_benchmark' => 'Industry Benchmark',
        'feature_adoption' => 'Feature Adoption Pattern',
        'ai_usage_pattern' => 'AI Usage Pattern',
        'cost_optimization' => 'Cost Optimization Opportunity',
        'quality_trend' => 'Quality Trend',
      ]);

    $fields['vertical'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Vertical'))
      ->setDescription(t('Vertical this insight applies to (or "all").'))
      ->setRequired(TRUE)
      ->setDefaultValue('all')
      ->setSettings(['max_length' => 64]);

    $fields['title'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Title'))
      ->setRequired(TRUE)
      ->setSettings(['max_length' => 255]);

    $fields['summary'] = BaseFieldDefinition::create('string_long')
      ->setLabel(t('Summary'))
      ->setDescription(t('Human-readable summary of the insight.'))
      ->setRequired(TRUE);

    $fields['data'] = BaseFieldDefinition::create('string_long')
      ->setLabel(t('Aggregated Data'))
      ->setDescription(t('JSON with anonymized aggregated statistics.'))
      ->setRequired(TRUE)
      ->setDefaultValue('{}');

    $fields['contributing_tenants'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Contributing Tenants'))
      ->setDescription(t('Number of tenants that contributed to this insight.'))
      ->setRequired(TRUE)
      ->setDefaultValue(0);

    $fields['confidence_score'] = BaseFieldDefinition::create('float')
      ->setLabel(t('Confidence Score'))
      ->setDescription(t('Statistical confidence of the insight (0-1).'))
      ->setDefaultValue(0.0);

    $fields['period_start'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Period Start'))
      ->setDescription(t('Start of the data period for this insight.'));

    $fields['period_end'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Period End'))
      ->setDescription(t('End of the data period for this insight.'));

    $fields['status'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Status'))
      ->setDefaultValue('active')
      ->setSetting('allowed_values', [
        'active' => 'Active',
        'superseded' => 'Superseded',
        'archived' => 'Archived',
      ]);

    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Created'));

    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public static function schema(EntityTypeInterface $entity_type): array {
    $schema = parent::schema($entity_type);
    $schema['indexes']['aggregated_insight__insight_type'] = ['insight_type'];
    $schema['indexes']['aggregated_insight__vertical'] = ['vertical'];
    $schema['indexes']['aggregated_insight__status'] = ['status'];
    return $schema;
  }

  /**
   * Gets the insight type.
   */
  public function getInsightType(): string {
    return $this->get('insight_type')->value ?? '';
  }

  /**
   * Gets the title.
   */
  public function getTitle(): string {
    return $this->get('title')->value ?? '';
  }

  /**
   * Gets the summary.
   */
  public function getSummary(): string {
    return $this->get('summary')->value ?? '';
  }

  /**
   * Gets the contributing tenants count.
   */
  public function getContributingTenants(): int {
    return (int) ($this->get('contributing_tenants')->value ?? 0);
  }

  /**
   * Gets the confidence score.
   */
  public function getConfidenceScore(): float {
    return (float) ($this->get('confidence_score')->value ?? 0.0);
  }

  /**
   * Gets the aggregated data as decoded array.
   */
  public function getData(): array {
    $raw = $this->get('data')->value ?? '{}';
    return json_decode($raw, TRUE) ?: [];
  }

  /**
   * Whether this insight meets k-anonymity (min 5 tenants).
   */
  public function meetsKAnonymity(): bool {
    return $this->getContributingTenants() >= 5;
  }

}
