<?php

declare(strict_types=1);

namespace Drupal\jaraba_ai_agents\Service;

use Drupal\Core\StringTranslation\StringTranslationTrait;

/**
 * AI Transparency labels per EU AI Act Art. 50.
 *
 * Generates mandatory transparency disclosures for AI-generated content.
 * Users must always be informed when they interact with AI or receive
 * AI-generated content.
 *
 * No LLM dependency — purely deterministic label generation.
 *
 * @see https://eur-lex.europa.eu/eli/reg/2024/1689/oj (Art. 50)
 */
final class AiTransparencyService {

  use StringTranslationTrait;

  /**
   * Generates a transparency label for AI-generated content.
   *
   * @param string $agentId
   *   The agent that generated the content.
   * @param string $action
   *   The action performed.
   * @param array $context
   *   Optional: risk_level, vertical.
   *
   * @return array{label: string, css_class: string, aria_label: string, risk_level: string, metadata: array}
   *   Label data for rendering.
   */
  public function getLabel(string $agentId, string $action, array $context = []): array {
    $riskLevel = $context['risk_level'] ?? 'limited';

    $label = match ($riskLevel) {
      'high' => (string) $this->t('AI-Generated (High Risk)'),
      'limited' => (string) $this->t('AI-Generated'),
      'minimal' => (string) $this->t('AI-Assisted'),
      default => (string) $this->t('AI-Generated'),
    };

    $ariaLabel = match ($riskLevel) {
      'high' => (string) $this->t('This content was generated by AI and classified as high risk. Human review is required.'),
      'limited' => (string) $this->t('This content was generated by AI.'),
      'minimal' => (string) $this->t('This content was created with AI assistance.'),
      default => (string) $this->t('This content was generated by AI.'),
    };

    $cssClass = 'ai-transparency-label ai-transparency-label--' . $riskLevel;

    return [
      'label' => $label,
      'css_class' => $cssClass,
      'aria_label' => $ariaLabel,
      'risk_level' => $riskLevel,
      'metadata' => [
        'agent_id' => $agentId,
        'action' => $action,
        'generated_at' => date('c'),
        'eu_ai_act_art' => '50',
      ],
    ];
  }

  /**
   * Generates transparency metadata for API responses.
   *
   * @param string $agentId
   *   The agent that generated the response.
   * @param string $action
   *   The action performed.
   * @param string $riskLevel
   *   The risk classification level.
   *
   * @return array
   *   Metadata to include in API response headers or body.
   */
  public function getApiTransparencyMetadata(string $agentId, string $action, string $riskLevel): array {
    return [
      'ai_generated' => TRUE,
      'ai_agent' => $agentId,
      'ai_action' => $action,
      'risk_classification' => $riskLevel,
      'transparency_notice' => 'This content was generated by an AI system.',
      'regulation' => 'EU AI Act (Regulation 2024/1689), Art. 50',
      'timestamp' => date('c'),
    ];
  }

  /**
   * Checks if transparency label is required for a given risk level.
   *
   * @param string $riskLevel
   *   The risk level.
   *
   * @return bool
   *   TRUE if transparency label is required.
   */
  public function isLabelRequired(string $riskLevel): bool {
    return in_array($riskLevel, [
      AiRiskClassificationService::RISK_HIGH,
      AiRiskClassificationService::RISK_LIMITED,
    ], TRUE);
  }

}
