<?php

declare(strict_types=1);

namespace Drupal\jaraba_support\Entity;

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Interface for Ticket Message entities.
 */
interface TicketMessageInterface extends ContentEntityInterface {

  /**
   * Gets the parent ticket entity.
   */
  public function getTicket(): ?SupportTicketInterface;

  /**
   * Gets the author type (customer, agent, ai, system).
   */
  public function getAuthorType(): string;

  /**
   * Checks if this is an internal note (not visible to tenant).
   */
  public function isInternalNote(): bool;

  /**
   * Checks if this message was generated by AI.
   */
  public function isAiGenerated(): bool;

}
