<?php

/**
 * @file
 * HOOK-THEME-TEMPLATE-PARITY-001: Bidirectional parity hook_theme() <-> .html.twig.
 *
 * Checks:
 * 1. Forward: Every template declared in hook_theme() has a corresponding .html.twig file.
 * 2. Reverse: Every .html.twig file in templates/ (excluding partials _*) has a hook_theme() entry.
 *
 * Excludes entity templates (auto-generated by Drupal from annotations), view mode
 * templates, and field templates.
 *
 * Usage: php scripts/validation/validate-hook-theme-template-parity.php
 * Exit:  0 = pass (warn_check)
 */

declare(strict_types=1);

$root = dirname(__DIR__, 2);
$modulesDir = $root . '/web/modules/custom';

if (!is_dir($modulesDir)) {
  fwrite(STDERR, "ERROR: $modulesDir not found\n");
  exit(1);
}

echo "\033[36m╔══════════════════════════════════════════════════════════╗\033[0m\n";
echo "\033[36m║  HOOK-THEME-TEMPLATE-PARITY-001                         ║\033[0m\n";
echo "\033[36m║  Bidirectional hook_theme() <-> Template Parity          ║\033[0m\n";
echo "\033[36m╚══════════════════════════════════════════════════════════╝\033[0m\n\n";

$errors = [];
$warnings = [];
$passes = [];

// ─────────────────────────────────────────────────────────────
// Step 1: Collect all module directories (top-level + submodules).
// ─────────────────────────────────────────────────────────────
$topDirs = glob("$modulesDir/*/") ?: [];
$subDirs = glob("$modulesDir/*/modules/*/") ?: [];
$allModuleDirs = array_merge($topDirs, $subDirs);

// ─────────────────────────────────────────────────────────────
// Step 2: Discover entity type IDs to exclude entity templates.
// Entity templates are auto-generated by Drupal's EntityViewBuilder
// from @ContentEntityType annotations — they don't need hook_theme().
// ─────────────────────────────────────────────────────────────
$entityTypeIds = [];

$entityFiles = array_merge(
  glob("$modulesDir/*/src/Entity/*.php") ?: [],
  glob("$modulesDir/*/modules/*/src/Entity/*.php") ?: []
);

foreach ($entityFiles as $entityFile) {
  $content = file_get_contents($entityFile);
  if ($content === false) {
    continue;
  }
  // Match @ContentEntityType id in annotations.
  if (preg_match('/@ContentEntityType\b/', $content) && preg_match('/\*\s+"?id"?\s*=\s*"([^"]+)"/', $content, $m)) {
    $entityTypeIds[] = $m[1];
  }
  // Also match #[ContentEntityType] attribute style.
  if (preg_match('/#\[ContentEntityType\b/', $content) && preg_match('/id:\s*[\'"]([^\'"]+)[\'"]/', $content, $m)) {
    $entityTypeIds[] = $m[1];
  }
}

$entityTypeIds = array_unique($entityTypeIds);

// Build template name patterns for entity types (entity_type_id -> entity-type-id).
$entityTemplateNames = [];
foreach ($entityTypeIds as $typeId) {
  $entityTemplateNames[] = str_replace('_', '-', $typeId);
}

/**
 * Check if a template name corresponds to an entity template.
 *
 * Entity templates follow the pattern: {entity-type-id}.html.twig
 * or {entity-type-id}--{view-mode}.html.twig
 */
function isEntityTemplate(string $templateBasename, array $entityTemplateNames): bool {
  // Remove .html.twig suffix.
  $name = preg_replace('/\.html\.twig$/', '', $templateBasename);
  if ($name === null) {
    return false;
  }

  foreach ($entityTemplateNames as $entityName) {
    // Exact match or view mode variant (entity-type--view-mode).
    if ($name === $entityName || str_starts_with($name, $entityName . '--')) {
      return true;
    }
  }

  return false;
}

/**
 * Check if a template name is a field or view mode template (excluded).
 */
function isFieldOrViewModeTemplate(string $templateBasename): bool {
  $name = preg_replace('/\.html\.twig$/', '', $templateBasename);
  if ($name === null) {
    return false;
  }

  // Field templates: field--*.html.twig.
  if (str_starts_with($name, 'field--') || str_starts_with($name, 'field-')) {
    return true;
  }

  // Views templates: views-view-*.html.twig.
  if (str_starts_with($name, 'views-view')) {
    return true;
  }

  // Block templates: block--*.html.twig.
  if (str_starts_with($name, 'block--')) {
    return true;
  }

  return false;
}

// ─────────────────────────────────────────────────────────────
// Step 3: Parse hook_theme() from all .module files.
// Build map: module_name -> [template_name => hook_name, ...]
// ─────────────────────────────────────────────────────────────
$hookThemeTemplates = []; // module_name => [template_name => hook_name]
$moduleFileMap = [];      // module_name => module_dir

$moduleFiles = array_merge(
  glob("$modulesDir/*/*.module") ?: [],
  glob("$modulesDir/*/modules/*/*.module") ?: []
);

$totalHooksFound = 0;

foreach ($moduleFiles as $moduleFile) {
  $content = file_get_contents($moduleFile);
  if ($content === false) {
    continue;
  }

  // Find hook_theme() function. Match: function {module}_theme(...)
  if (!preg_match('/function\s+(\w+)_theme\s*\(/', $content)) {
    continue;
  }

  $moduleName = basename(dirname($moduleFile));
  // For submodules, dirname is the submodule dir.
  if (basename(dirname(dirname($moduleFile))) === 'modules') {
    // It's a submodule: custom/parent/modules/submodule/submodule.module
    $moduleName = basename(dirname($moduleFile));
  }

  $moduleDir = dirname($moduleFile);
  $moduleFileMap[$moduleName] = $moduleDir;

  // Extract the hook_theme function body.
  if (!preg_match('/function\s+\w+_theme\s*\([^)]*\)\s*(?::\s*array\s*)?\{(.*?)^\}/ms', $content, $funcMatch)) {
    continue;
  }

  $funcBody = $funcMatch[1];

  if (!isset($hookThemeTemplates[$moduleName])) {
    $hookThemeTemplates[$moduleName] = [];
  }

  // Strategy: find the return statement's array, then parse top-level keys only.
  // We find 'return [' and then walk through the array tracking bracket depth.
  // Top-level hook entries are at depth 1 (inside the return array).
  $returnPos = strpos($funcBody, 'return');
  if ($returnPos === false) {
    continue;
  }

  $bracketStart = strpos($funcBody, '[', $returnPos);
  if ($bracketStart === false) {
    continue;
  }

  // Walk through the return array, tracking depth.
  // At depth 1, any 'key' => [ is a hook entry.
  $depth = 0;
  $hookEntries = []; // [hook_name => block_content]
  $currentHookName = null;
  $currentHookStart = 0;
  $bodyLen = strlen($funcBody);
  $inString = false;
  $stringChar = '';

  for ($i = $bracketStart, $len = $bodyLen; $i < $len; $i++) {
    $ch = $funcBody[$i];

    // Handle string literals.
    if ($inString) {
      if ($ch === '\\') {
        $i++;
        continue;
      }
      if ($ch === $stringChar) {
        $inString = false;
      }
      continue;
    }

    // Handle comments.
    if ($ch === '/' && $i + 1 < $len) {
      $next = $funcBody[$i + 1];
      if ($next === '/') {
        // Single-line comment — skip to end of line.
        $eol = strpos($funcBody, "\n", $i);
        if ($eol !== false) {
          $i = $eol;
        }
        continue;
      }
    }

    if ($ch === "'" || $ch === '"') {
      $inString = true;
      $stringChar = $ch;
      continue;
    }

    if ($ch === '[') {
      $depth++;

      // If entering depth 2 and we just found a hook name, record start.
      if ($depth === 2 && $currentHookName !== null) {
        $currentHookStart = $i;
      }
      continue;
    }

    if ($ch === ']') {
      // If closing depth 2, we have the full hook block.
      if ($depth === 2 && $currentHookName !== null) {
        $hookBlock = substr($funcBody, $currentHookStart, $i - $currentHookStart + 1);
        $hookEntries[$currentHookName] = $hookBlock;
        $currentHookName = null;
      }
      $depth--;
      if ($depth === 0) {
        break; // End of return array.
      }
      continue;
    }

    // At depth 1, look for 'hook_name' => patterns.
    if ($depth === 1 && ($ch === "'" || $ch === '"')) {
      // This was already handled by string tracking above, but we need to
      // capture the key. Re-check: we set inString above, so we need a
      // different approach. Let's use regex on the remaining text from here.
    }
  }

  // The bracket-walking approach above handles strings but the key detection
  // needs a second pass. Let's use a line-based approach on the function body
  // that only matches keys at the correct indentation (depth 1 = typically 4 spaces).
  // Reset and use a more robust approach.
  $hookEntries = [];

  // Find the return [ line and determine its indentation.
  $lines = explode("\n", $funcBody);
  $inReturn = false;
  $returnDepth = 0;
  $bracketDepth = 0;
  $currentHookName = null;
  $currentHookBlock = '';
  $hookStartDepth = 0;

  foreach ($lines as $line) {
    // Detect start of return array.
    if (!$inReturn && preg_match('/\breturn\s*\[/', $line)) {
      $inReturn = true;
      // Count brackets on this line.
      $bracketDepth += substr_count($line, '[') - substr_count($line, ']');
      continue;
    }

    if (!$inReturn) {
      continue;
    }

    // Count brackets (naive — doesn't handle strings, but works for typical hook_theme code).
    $openBrackets = substr_count($line, '[');
    $closeBrackets = substr_count($line, ']');

    if ($currentHookName !== null) {
      $currentHookBlock .= $line . "\n";
      $bracketDepth += $openBrackets - $closeBrackets;

      // Hook block closed when we return to depth 1.
      if ($bracketDepth <= 1) {
        $hookEntries[$currentHookName] = $currentHookBlock;
        $currentHookName = null;
        $currentHookBlock = '';
      }
      continue;
    }

    // At depth 1, look for top-level hook key: 'hook_name' => [
    if ($bracketDepth === 1 && preg_match("/^\s+['\"]([a-z][a-z0-9_]*?)['\"]\s*=>\s*\[/", $line, $m)) {
      $currentHookName = $m[1];
      $currentHookBlock = $line . "\n";
      $bracketDepth += $openBrackets - $closeBrackets;

      // If bracket closed on same line, save immediately.
      if ($bracketDepth <= 1) {
        $hookEntries[$currentHookName] = $currentHookBlock;
        $currentHookName = null;
        $currentHookBlock = '';
      }
      continue;
    }

    $bracketDepth += $openBrackets - $closeBrackets;

    if ($bracketDepth <= 0) {
      break; // End of return array.
    }
  }

  foreach ($hookEntries as $hookName => $hookBlock) {
    // Skip entries with 'render element' — these are render element hooks, not template hooks.
    if (preg_match("/['\"]render\s+element['\"]/", $hookBlock)) {
      continue;
    }

    $totalHooksFound++;

    // Determine template name: explicit 'template' key or derived from hook name.
    $templateName = str_replace('_', '-', $hookName);
    if (preg_match("/['\"]template['\"]\s*=>\s*['\"]([^'\"]+)['\"]/", $hookBlock, $tplMatch)) {
      $templateName = $tplMatch[1];
    }

    $hookThemeTemplates[$moduleName][$templateName] = $hookName;
  }
}

// ─────────────────────────────────────────────────────────────
// Step 4 (Forward): Check each hook_theme template has a .twig file.
// ─────────────────────────────────────────────────────────────
$checkedForward = 0;

foreach ($hookThemeTemplates as $moduleName => $templates) {
  $moduleDir = $moduleFileMap[$moduleName] ?? null;
  if ($moduleDir === null) {
    continue;
  }

  foreach ($templates as $templateName => $hookName) {
    $checkedForward++;
    $twigFile = $moduleDir . '/templates/' . $templateName . '.html.twig';

    // Also check subdirectories of templates/.
    $found = false;
    if (file_exists($twigFile)) {
      $found = true;
    } else {
      // Search recursively in templates/.
      $templatesDir = $moduleDir . '/templates';
      if (is_dir($templatesDir)) {
        $rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($templatesDir));
        foreach ($rii as $file) {
          if ($file->isFile() && $file->getFilename() === $templateName . '.html.twig') {
            $found = true;
            break;
          }
        }
      }
    }

    if ($found) {
      $passes[] = "[$moduleName] hook '$hookName' -> $templateName.html.twig";
    } else {
      $errors[] = "[$moduleName] hook '$hookName' declares template '$templateName' but file NOT found in templates/";
    }
  }
}

// ─────────────────────────────────────────────────────────────
// Step 5 (Reverse): Check each .twig file has a hook_theme entry.
// Skip partials (_*), entity templates, field/view mode templates.
// ─────────────────────────────────────────────────────────────
$checkedReverse = 0;

foreach ($allModuleDirs as $dir) {
  $moduleName = basename(rtrim($dir, '/'));
  $templatesDir = rtrim($dir, '/') . '/templates';

  if (!is_dir($templatesDir)) {
    continue;
  }

  $rii = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($templatesDir));
  $moduleTemplateMap = $hookThemeTemplates[$moduleName] ?? [];

  foreach ($rii as $file) {
    if (!$file->isFile()) {
      continue;
    }

    $filename = $file->getFilename();
    if (!str_ends_with($filename, '.html.twig')) {
      continue;
    }

    // Skip partials (files starting with _).
    if (str_starts_with($filename, '_')) {
      continue;
    }

    // Skip entity templates.
    if (isEntityTemplate($filename, $entityTemplateNames)) {
      continue;
    }

    // Skip field/view mode/block templates.
    if (isFieldOrViewModeTemplate($filename)) {
      continue;
    }

    $checkedReverse++;

    $templateName = preg_replace('/\.html\.twig$/', '', $filename);
    if ($templateName === null) {
      continue;
    }

    // Check if this template is declared in this module's hook_theme().
    if (isset($moduleTemplateMap[$templateName])) {
      // Already counted in forward pass.
      continue;
    }

    // Not found in this module's hook_theme — orphan.
    $relativePath = str_replace($root . '/', '', (string) $file->getPathname());
    $warnings[] = "[$moduleName] Template '$filename' exists but has NO hook_theme() entry — orphan ($relativePath)";
  }
}

// ─────────────────────────────────────────────────────────────
// Report.
// ─────────────────────────────────────────────────────────────
echo "Scanned: " . count($moduleFiles) . " module files, $totalHooksFound hook_theme entries\n";
echo "Checked: $checkedForward forward (hook->twig), $checkedReverse reverse (twig->hook)\n\n";

foreach ($passes as $p) {
  echo "  \033[32m✓\033[0m $p\n";
}
foreach ($warnings as $w) {
  echo "  \033[33m⚠\033[0m $w\n";
}
foreach ($errors as $e) {
  echo "  \033[31m✗\033[0m $e\n";
}

$totalChecks = count($passes) + count($errors);
echo "\n\033[36m═══════════════════════════════════════════════════════════\033[0m\n";
echo "  RESULT: " . count($passes) . "/$totalChecks PASS";
if (!empty($warnings)) {
  echo ", " . count($warnings) . " WARN";
}
if (!empty($errors)) {
  echo ", \033[31m" . count($errors) . " FAIL\033[0m";
}
echo "\n\033[36m═══════════════════════════════════════════════════════════\033[0m\n";

// warn_check: exit 0 always. Missing templates and orphans are reported but not blocking.
exit(0);
