<?php

/**
 * @file
 * Validator: DAILY-ACTION-ROUTES-001 — route existence for DailyActions & SetupWizardSteps.
 *
 * Verifies that every DailyAction::getRoute() and SetupWizardStep::getRoute()
 * returns a route name that exists in some module's routing.yml.
 *
 * Usage: php scripts/validation/validate-daily-action-routes.php
 */

declare(strict_types=1);

$errors = [];
$passes = [];

$modulesDir = __DIR__ . '/../../web/modules/custom';

// Step 1: Collect ALL route names from ALL routing.yml files.
$allRoutes = [];
$routingFiles = glob($modulesDir . '/*/*.routing.yml');
foreach ($routingFiles as $routingFile) {
  $content = file_get_contents($routingFile);
  // Route names are top-level YAML keys (no indentation, ending with :).
  if (preg_match_all('/^(\S[^:\s]+)\s*:/m', $content, $routeMatches)) {
    foreach ($routeMatches[1] as $routeName) {
      // Skip YAML anchors and comments.
      if (strpos($routeName, '#') === 0 || strpos($routeName, '&') === 0) {
        continue;
      }
      $allRoutes[$routeName] = basename(dirname($routingFile));
    }
  }
}

// Also add well-known Drupal core routes that modules commonly reference.
$coreRoutes = [
  'system.admin',
  'system.admin_content',
  'system.admin_structure',
  'system.theme_settings',
  'system.theme_settings_theme',
  'user.page',
  'user.login',
  'user.logout',
  'user.register',
  'user.pass',
  'entity.user.canonical',
  'entity.user.edit_form',
  'entity.user.collection',
  '<front>',
  '<nolink>',
  '<none>',
];
foreach ($coreRoutes as $r) {
  $allRoutes[$r] = 'core';
}

// Add entity routes that are auto-generated by Drupal.
// Pattern: entity.{entity_type}.{operation}
$entityAnnotations = glob($modulesDir . '/*/src/Entity/*.php');
foreach ($entityAnnotations as $entityFile) {
  $content = file_get_contents($entityFile);
  // Extract link templates from annotation.
  if (preg_match_all('/"\w+" = "([^"]+)"/', $content, $linkMatches)) {
    // These generate routes like entity.{type}.canonical, etc.
  }
  // Extract entity type ID.
  if (preg_match('/\*\s+id\s*=\s*"(\w+)"/', $content, $idMatch)) {
    $eid = $idMatch[1];
    // Common auto-generated routes.
    $autoRoutes = [
      "entity.{$eid}.canonical",
      "entity.{$eid}.edit_form",
      "entity.{$eid}.delete_form",
      "entity.{$eid}.add_form",
      "entity.{$eid}.collection",
    ];
    foreach ($autoRoutes as $ar) {
      $allRoutes[$ar] = 'auto';
    }
  }
}

$totalRoutes = count($allRoutes);

// Step 2: Scan DailyActions and SetupWizard directories.
$scanDirs = [
  'DailyActions' => glob($modulesDir . '/*/src/DailyActions/*.php'),
  'DailyAction' => glob($modulesDir . '/*/src/DailyAction/*.php'),
  'SetupWizard' => glob($modulesDir . '/*/src/SetupWizard/*.php'),
];

$checkedItems = [];

foreach ($scanDirs as $type => $files) {
  foreach ($files as $file) {
    $content = file_get_contents($file);
    $basename = basename($file, '.php');
    $moduleName = basename(dirname(dirname(dirname($file))));

    // Extract getRoute() method and its return value.
    if (!preg_match('/function\s+getRoute\s*\(\s*\)/', $content)) {
      continue;
    }

    // Find return statements inside getRoute().
    // Simple approach: find the method and extract return value.
    $funcPos = strpos($content, 'function getRoute()');
    if ($funcPos === FALSE) {
      // Try with return type hint.
      if (preg_match('/function\s+getRoute\s*\(\s*\)\s*:\s*\??\s*string/', $content)) {
        $funcPos = 0;
        if (preg_match('/function\s+getRoute\s*\(\s*\)\s*:\s*\??\s*string/', $content, $m, PREG_OFFSET_CAPTURE)) {
          $funcPos = $m[0][1];
        }
      }
      if ($funcPos === FALSE || $funcPos === 0) {
        continue;
      }
    }

    // Extract method body.
    $bracePos = strpos($content, '{', $funcPos);
    if ($bracePos === FALSE) {
      continue;
    }
    $depth = 0;
    $methodBody = '';
    for ($i = $bracePos; $i < strlen($content); $i++) {
      if ($content[$i] === '{') {
        $depth++;
      } elseif ($content[$i] === '}') {
        $depth--;
      }
      $methodBody .= $content[$i];
      if ($depth === 0) {
        break;
      }
    }

    // Extract return values (could be multiple due to conditionals).
    $routes = [];
    if (preg_match_all("/return\s+'([^']+)'/", $methodBody, $returnMatches)) {
      $routes = $returnMatches[1];
    }
    if (preg_match_all('/return\s+"([^"]+)"/', $methodBody, $returnMatches2)) {
      $routes = array_merge($routes, $returnMatches2[1]);
    }

    // Handle return NULL (optional route).
    $hasNullReturn = (strpos($methodBody, 'return NULL') !== FALSE || strpos($methodBody, 'return null') !== FALSE);

    if (empty($routes) && !$hasNullReturn) {
      // Could be returning a variable or expression — skip.
      continue;
    }

    foreach ($routes as $route) {
      $label = "{$type}/{$basename}";

      if (isset($allRoutes[$route])) {
        $passes[] = "CHECK: {$label} — route '{$route}' exists";
      } else {
        $errors[] = "FAIL: {$label} — route '{$route}' NOT found in any routing.yml";
      }
      $checkedItems[] = $label;
    }
  }
}

// RESULTS
$total = count($errors) + count($passes);
echo "\n=== DAILY-ACTION-ROUTES-001 ===\n\n";
foreach ($passes as $msg) {
  echo "  ✅ $msg\n";
}
foreach ($errors as $msg) {
  echo "  ❌ $msg\n";
}
echo "\n--- Score: " . count($passes) . "/$total checks passed ({$totalRoutes} routes indexed) ---\n\n";
exit(empty($errors) ? 0 : 1);
