<?php

/**
 * @file
 * ENV-BOOTSTRAP-001: Early environment variable loader.
 *
 * This file MUST be included BEFORE settings.secrets.php in settings.php.
 * It calls putenv() to make API keys available via getenv() for the rest
 * of the settings chain.
 *
 * LOAD ORDER (settings.php):
 *   1. settings.env.php      ← THIS FILE: putenv() calls
 *   2. settings.cdn.php      ← reads getenv('CDN_BASE_URL')
 *   3. settings.secrets.php  ← reads getenv('RECAPTCHA_*', 'STRIPE_*', etc.)
 *   4. settings.ai-queues.php
 *   5. settings.local.php    ← DB credentials + local overrides ONLY
 *
 * WHY THIS EXISTS:
 * The previous architecture appended putenv() calls to settings.local.php,
 * which loads LAST. But settings.secrets.php (which maps env vars to $config
 * overrides) loads BEFORE settings.local.php. Result: getenv() returned
 * false for all API keys in production, causing reCAPTCHA, Stripe, and
 * OAuth failures.
 *
 * GENERATION:
 * This file is auto-generated by CI/CD (.github/workflows/deploy.yml).
 * It is NOT tracked in git (.gitignore).
 *
 * SECURITY:
 * - Permissions: 440 (read-only for web user)
 * - Parent directory: 555 (no file creation)
 * - Contains only putenv() calls — no logic, no config overrides
 *
 * @see config/deploy/settings.secrets.php (reads these env vars)
 * @see .env.example (complete variable documentation)
 */

// This file is auto-generated by CI/CD. Do not edit manually.
// To update, re-run the deploy pipeline or use:
//   ssh $IONOS_USER@$IONOS_HOST 'cd ~/JarabaImpactPlatformSaaS && nano config/deploy/settings.env.php'

// =============================================================================
// WhatsApp Cloud API — jaraba_whatsapp module (SECRET-MGMT-001).
// Replace PLACEHOLDER values with real credentials from Meta Business Manager.
// =============================================================================
putenv('WHATSAPP_VERIFY_TOKEN=andalucia_ei_wa_24a8477f10cf092c');
putenv('WHATSAPP_APP_SECRET=PLACEHOLDER_obtener_de_meta_configuracion_basica');
putenv('WHATSAPP_ACCESS_TOKEN=PLACEHOLDER_obtener_de_meta_getting_started');
putenv('WHATSAPP_PHONE_NUMBER_ID=PLACEHOLDER_obtener_tras_migrar_numero');
putenv('WHATSAPP_BUSINESS_ACCOUNT_ID=PLACEHOLDER_obtener_de_meta_getting_started');
putenv('WA_ENCRYPTION_KEY=sDC22lM5cGB+6TLO/wxRioCOtcZ+4Ta8SS3OZpYkc7I=');
putenv('WA_JOSE_PHONE=+34623174304');
putenv('WA_JOSE_EMAIL=contacto@plataformadeecosistemas.com');
