<?php

/**
 * @file
 * ENV-BOOTSTRAP-001: Early environment variable loader.
 *
 * This file MUST be included BEFORE settings.secrets.php in settings.php.
 * It calls putenv() to make API keys available via getenv() for the rest
 * of the settings chain.
 *
 * LOAD ORDER (settings.php):
 *   1. settings.env.php      ← THIS FILE: putenv() calls
 *   2. settings.cdn.php      ← reads getenv('CDN_BASE_URL')
 *   3. settings.secrets.php  ← reads getenv('RECAPTCHA_*', 'STRIPE_*', etc.)
 *   4. settings.ai-queues.php
 *   5. settings.local.php    ← DB credentials + local overrides ONLY
 *
 * WHY THIS EXISTS:
 * The previous architecture appended putenv() calls to settings.local.php,
 * which loads LAST. But settings.secrets.php (which maps env vars to $config
 * overrides) loads BEFORE settings.local.php. Result: getenv() returned
 * false for all API keys in production, causing reCAPTCHA, Stripe, and
 * OAuth failures.
 *
 * GENERATION:
 * This file is auto-generated by CI/CD (.github/workflows/deploy.yml).
 * It is NOT tracked in git (.gitignore).
 *
 * SECURITY:
 * - Permissions: 440 (read-only for web user)
 * - Parent directory: 555 (no file creation)
 * - Contains only putenv() calls — no logic, no config overrides
 *
 * @see config/deploy/settings.secrets.php (reads these env vars)
 * @see .env.example (complete variable documentation)
 */

// This file is auto-generated by CI/CD. Do not edit manually.
// To update, re-run the deploy pipeline or use:
//   ssh $IONOS_USER@$IONOS_HOST 'cd ~/JarabaImpactPlatformSaaS && nano config/deploy/settings.env.php'
